"""Data models describing salon masters and their schedules."""

from django.conf import settings
from django.db import models

from services.models import Service


class MasterProfile(models.Model):
    """Profile data for a salon master.

    Description:
        Stores additional information about a master, including specialization
        and services they provide. The profile is linked to a user account with
        the master role.

    Args:
        models.Model: Django base model class.

    Returns:
        MasterProfile: Persisted master profile.

    Raises:
        ValueError: Raised when required fields are missing.

    Examples:
        >>> profile = MasterProfile(user=user, bio="Опыт 5 лет")
        >>> profile.services.count() >= 0
        True
    """

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="master_profile",
        help_text="Пользователь, связанный с профилем мастера.",
    )
    bio = models.TextField(
        blank=True,
        help_text="Краткое описание опыта и специализации мастера.",
    )
    services = models.ManyToManyField(
        Service,
        related_name="masters",
        help_text="Список услуг, которые оказывает мастер.",
    )
    is_active = models.BooleanField(
        default=True,
        help_text="Признак активности мастера в расписании.",
    )

    class Meta:
        """Model metadata for MasterProfile."""

        verbose_name = "Мастер"
        verbose_name_plural = "Мастера"

    def __str__(self) -> str:
        """Return the master full name for display.

        Description:
            Uses the related user to display the master in admin and lists.

        Args:
            None

        Returns:
            str: Full name or username for the master.

        Raises:
            None

        Examples:
            >>> str(MasterProfile(user=user))
            'Иван Иванов'
        """

        return self.user.get_full_name() or self.user.username


class WorkingSlot(models.Model):
    """Represents a working time slot available for booking.

    Description:
        A working slot is a time interval for a master that can be booked
        by clients. Slots are generated by administrators and linked to
        appointments when booked.

    Args:
        models.Model: Django base model class.

    Returns:
        WorkingSlot: Persisted working slot.

    Raises:
        ValueError: Raised if slot times are inconsistent.

    Examples:
        >>> slot = WorkingSlot(master=profile, start_at=dt, end_at=dt2)
        >>> slot.is_available
        True
    """

    master = models.ForeignKey(
        MasterProfile,
        on_delete=models.CASCADE,
        related_name="working_slots",
        help_text="Мастер, которому принадлежит слот.",
    )
    start_at = models.DateTimeField(help_text="Начало рабочего слота.")
    end_at = models.DateTimeField(help_text="Окончание рабочего слота.")
    is_available = models.BooleanField(
        default=True,
        help_text="Флаг доступности слота для записи.",
    )

    class Meta:
        """Model metadata for WorkingSlot."""

        ordering = ["start_at"]
        verbose_name = "Рабочий слот"
        verbose_name_plural = "Рабочие слоты"

    def __str__(self) -> str:
        """Return a readable label for the slot.

        Description:
            Combines master name and start time for human-friendly display.

        Args:
            None

        Returns:
            str: Slot label with master and start time.

        Raises:
            None

        Examples:
            >>> str(slot)
            'Иван Иванов — 2026-05-01 10:00'
        """

        return f"{self.master} — {self.start_at:%Y-%m-%d %H:%M}"
