# Generated by Django 5.2.13 on 2026-04-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Краткое описание опыта и специализации мастера.')),
                ('is_active', models.BooleanField(default=True, help_text='Признак активности мастера в расписании.')),
                ('services', models.ManyToManyField(help_text='Список услуг, которые оказывает мастер.', related_name='masters', to='services.service')),
                ('user', models.OneToOneField(help_text='Пользователь, связанный с профилем мастера.', on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='WorkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(help_text='Начало рабочего слота.')),
                ('end_at', models.DateTimeField(help_text='Окончание рабочего слота.')),
                ('is_available', models.BooleanField(default=True, help_text='Флаг доступности слота для записи.')),
                ('master', models.ForeignKey(help_text='Мастер, которому принадлежит слот.', on_delete=django.db.models.deletion.CASCADE, related_name='working_slots', to='masters.masterprofile')),
            ],
            options={
                'verbose_name': 'Рабочий слот',
                'verbose_name_plural': 'Рабочие слоты',
                'ordering': ['start_at'],
            },
        ),
    ]
