# Generated by Django 5.2.13 on 2026-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название услуги.', max_length=120)),
                ('description', models.TextField(help_text='Подробное описание услуги.')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Длительность услуги в минутах.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость услуги в рублях.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Признак активности услуги для бронирования.')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
    ]
