# Generated by Django 5.2.13 on 2026-04-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='planned', help_text='Текущий статус записи.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления.')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные пожелания или комментарии клиента.')),
                ('client', models.ForeignKey(help_text='Клиент, записанный на услугу.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(help_text='Мастер, оказывающий услугу.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='masters.masterprofile')),
                ('service', models.ForeignKey(help_text='Выбранная услуга.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
                ('slot', models.OneToOneField(help_text='Рабочий слот, выбранный для записи.', on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='masters.workingslot')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
